### PR TITLE
Issue #12 - Add command process_payments

### LINKED ISSUE #12: New command process_payments
`django-admin process_payments [--from isodatetime --to isodatetime]`

Command `process_payments` will take all payments in state `IMPORTED` (with optional date limitation). For each payment, it calls one or more **payment processors**, until one of them succeeds or all processors return negative answer. If any payment processor returns `True`, payment will be marked as `PROCESSED`. Otherwise, payment will be marked as `DEFERRED` (new payment state).

Every processor is a Python class, that **MUST** implement following methods:
- `process_payment(BankPayment) -> bool`
  - This method will return `True` if payment is recognized and processed by the processor. Otherwise, this method returns `False`.

### PR DESCRIPTION
**Pull request by stinovlas**
Closes #12.

---
This change is [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/14)

### CODE REVIEW

**Comment by ziima** [comment]
Reviewed 6 of 11 files at r1.
Review status: 6 of 11 files reviewed at latest revision, all discussions resolved.

---

*[django_pain/management/commands/process_payments.py, line 18 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPCVj46cSNeWvHyJuj:-LEPCVj46cSNeWvHyJuk:b-6aa3nk) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/management/commands/process_payments.py#L18)):*
> ```Python
> 
>     def add_arguments(self, parser):
>         """Command takes one argument - dotted path to parser class."""
> ```

Incorrect docstrings and help

---

*[django_pain/management/commands/process_payments.py, line 34 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPD7khB7KAG1bny0xQ:-LEPD7khB7KAG1bny0xR:b-fxptfu) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/management/commands/process_payments.py#L34)):*
> ```Python
>             payments = payments.filter(create_time__lte=options['time_to'])
> 
>         processors = getattr(settings, 'PAIN_PROCESSORS', None)
> ```

`settings` are best used through an app settings application, such as https://github.com/Genida/django-appsettings, or at least a custom module.

Settings also needs to be documented, at least in README.

---

*[django_pain/management/commands/process_payments.py, line 41 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPDnU45vBL2ZjWcbvR:-LEPDnU45vBL2ZjWcbvS:bf518nw) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/management/commands/process_payments.py#L41)):*
> ```Python
>             for processor_str in processors:
>                 processor_class = module_loading.import_string(processor_str)
>                 processor = processor_class()
> ```

It would be better to load the processors first and then used them then to load them for each payment. https://docs.djangoproject.com/en/2.0/ref/utils/#django.utils.functional.cached_property may come handy for that

---

*[django_pain/management/commands/process_payments.py, line 45 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPEYR29UPnAdmFBfDO:-LEPEYR29UPnAdmFBfDP:b-cu8h52) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/management/commands/process_payments.py#L45)):*
> ```Python
>                 if processor.process_payment(payment):
>                     payment.state = PaymentState.PROCESSED
>                     payment.save()
> ```

I'd rather send a copy of `payment` to the processor. Otherwise the processor may (accidentally or intentionally) modify the payment data and this `save` would store them in database.

---

*[django_pain/management/commands/process_payments.py, line 48 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPEH6d2LUBgrWmSlL_:-LEPEH6d2LUBgrWmSlLa:b1ujt2v) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/management/commands/process_payments.py#L48)):*
> ```Python
>                     break
> 
>             if payment.state != PaymentState.PROCESSED:
> ```

Looks like a candidate for the `else` clause of the `for` cycle.

---

*[django_pain/processors/common.py, line 8 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPBwdO6fZjPa-PTlHM:-LEPBwdQBAGeJoUkYLso:b-uv7gfv) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/processors/common.py#L8)):*
> ```Python
> 
> class AbstractPaymentProcessor(ABC):
>     """Bank statement parser."""
> ```

Incorrect docstring.

---

*[django_pain/tests/commands/test_import_payments.py, line 1 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPFBhh-VnhC7IhXJm2:-LEPFBhh-VnhC7IhXJm3:b-rtm0o9) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/tests/commands/test_import_payments.py#L1)):*
> ```Python
> """Test import_payments command."""
> ```

I'd rather have this move separated. If not as an issue, at least as a commit.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/14)*

**Comment by ziima** [comment]
Review status: 6 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[django_pain/tests/commands/test_process_payments.py, line 27 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPFSCdDL4ShRw3wCez:-LEPFSCdDL4ShRw3wCf-:bc81mrq) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/tests/commands/test_process_payments.py#L27)):*
> ```Python
> 
> 
> @freeze_time('2018-01-01')
> ```

`testfixtures` can freeze time as well. But it may be a bit more difficult to use them.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/14)*

**Comment by stinovlas** [comment]
Review status: 6 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[django_pain/tests/commands/test_process_payments.py, line 27 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPFSCdDL4ShRw3wCez:-LETPqQND5cXavGw0y0z:ba9yffa) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/tests/commands/test_process_payments.py#L27)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

`testfixtures` can freeze time as well. But it may be a bit more difficult to use them.
</blockquote></details>

With `testfixtures`, I need to know in which module the `datetime` import needs to be overriden. This is Django-specific and can differ from version to version. I highly prefer `freezegun`, which is Django-version agnostic. It is another dependency, but only for testing, so it's not such a big deal. I think that advantages of writing less and more understandable code outweighs potential risks of introducing another testing dependency.

---

*[django_pain/tests/commands/test_import_payments.py, line 1 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPFBhh-VnhC7IhXJm2:-LETRLzYEQCY4RDsmG1J:b-y4sevk) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/tests/commands/test_import_payments.py#L1)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

I'd rather have this move separated. If not as an issue, at least as a commit.
</blockquote></details>

OK, separate commit it is.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/14)*

**Comment by stinovlas** [comment]
Review status: 5 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[django_pain/management/commands/process_payments.py, line 18 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPCVj46cSNeWvHyJuj:-LETVpqzDrT0YEOTQaR3:b-bw8e14) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/management/commands/process_payments.py#L18)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

Incorrect docstrings and help
</blockquote></details>

Updated.

---

*[django_pain/management/commands/process_payments.py, line 34 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPD7khB7KAG1bny0xQ:-LETWzlSAbEPu1lJ2vZd:b8oitcj) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/management/commands/process_payments.py#L34)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

`settings` are best used through an app settings application, such as https://github.com/Genida/django-appsettings, or at least a custom module.

Settings also needs to be documented, at least in README.

</blockquote></details>

I used recommended app setting. Still need to update README.

---

*[django_pain/management/commands/process_payments.py, line 41 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPDnU45vBL2ZjWcbvR:-LETX6pxCBbuV6qfLwqk:buyrzod) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/management/commands/process_payments.py#L41)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

It would be better to load the processors first and then used them then to load them for each payment. https://docs.djangoproject.com/en/2.0/ref/utils/#django.utils.functional.cached_property may come handy for that
</blockquote></details>

Done. I didn't need to use `cached_property`, app settings themselves do the caching.

---

*[django_pain/management/commands/process_payments.py, line 45 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPEYR29UPnAdmFBfDO:-LETXGIF6CrLSVIHqJAu:b-sg30dg) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/management/commands/process_payments.py#L45)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

I'd rather send a copy of `payment` to the processor. Otherwise the processor may (accidentally or intentionally) modify the payment data and this `save` would store them in database.
</blockquote></details>

Agreed, I create a deepcopy now.

---

*[django_pain/management/commands/process_payments.py, line 48 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPEH6d2LUBgrWmSlL_:-LETXLv164zxjGTyddrL:b-rqkbtt) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/management/commands/process_payments.py#L48)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

Looks like a candidate for the `else` clause of the `for` cycle.
</blockquote></details>

Yeah, updated.

---

*[django_pain/processors/common.py, line 8 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPBwdO6fZjPa-PTlHM:-LETXP_d9Riyw0RdreeM:b-bw8e14) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/processors/common.py#L8)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

Incorrect docstring.
</blockquote></details>

Updated.

---

*[django_pain/tests/commands/test_import_payments.py, line 1 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPFBhh-VnhC7IhXJm2:-LETXSba716ae0td3g0h:b-8iagho) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/tests/commands/test_import_payments.py#L1)):*
<details><summary><i>Previously, stinovlas (Jan Musílek) wrote…</i></summary><blockquote>

OK, separate commit it is.
</blockquote></details>

I separated this rename to separate commit.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/14)*

**Comment by stinovlas** [comment]
*[django_pain/management/commands/process_payments.py, line 34 at r1](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEPD7khB7KAG1bny0xQ:-LETZLr92IboBh9SwjO4:b7d1s2o) ([raw file](https://github.com/stinovlas/django-pain/blob/2067a3e8d055fc1b0bdffd8d9dd8022d273b015c/django_pain/management/commands/process_payments.py#L34)):*
<details><summary><i>Previously, stinovlas (Jan Musílek) wrote…</i></summary><blockquote>

I used recommended app setting. Still need to update README.
</blockquote></details>

README updated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/14)*

**Comment by ziima** [comment]
Reviewed 2 of 11 files at r1, 6 of 7 files at r2.
Review status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @stinovlas and @ziima)

---

*[README.rst, line 21 at r2](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEhrHRWBjZHNFTfwPZV:-LEhrHRWBjZHNFTfwPZW:bskp01x) ([raw file](https://github.com/stinovlas/django-pain/blob/52954258b66d7a56e7914aca2623aeab52529077/README.rst#L21)):*
> ```reStructuredText
> 
> ``PAIN_PROCESSORS``
> ^^^^^^^^^^^^^^^^^^^
> ```

According to our RST style, this header should be marked with `====`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/14)*

**Comment by stinovlas** [comment]
*[README.rst, line 21 at r2](https://reviewable.io/reviews/stinovlas/django-pain/14#-LEhrHRWBjZHNFTfwPZV:-LEhxoUo72SfK3BjYIc9:b-bw8e14) ([raw file](https://github.com/stinovlas/django-pain/blob/52954258b66d7a56e7914aca2623aeab52529077/README.rst#L21)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

According to our RST style, this header should be marked with `====`.
</blockquote></details>

Updated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/14)*

**Comment by ziima** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/14#-:-LEigSeBDuhUU-_B8Ugp:bnfp4nl)*

**Review by ziima — APPROVED** [review]

**Comment by stinovlas** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/14)*

**Pull request merged**
