### PR TITLE
Add PaymentsListView and template

### LINKED ISSUE #8: Create view with payments list
- [ ] create view `PaymentListView`
- [ ] create template with list of payments
- [ ] create application `urls.py`

### PR DESCRIPTION
**Pull request by stinovlas**
Closes #8.

- [x] view `PaymentListView`
- [x] template `payments_list.html`
- [x] edit `urls.py`

---
This change is [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/9)

### CODE REVIEW

**Comment by ziima** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[django_pain/urls.py, line 6 at r1](https://reviewable.io/reviews/stinovlas/django-pain/9#-LCiDH0iCpmYqmrPiAQ-:-LCiDH0iCpmYqmrPiAQ0:boq81zs) ([raw file](https://github.com/stinovlas/django-pain/blob/43f892155a9361f95837b2ff35492f061010896a/django_pain/urls.py#L6)):*
> ```Python
> from .views import PaymentListView
> 
> urlpatterns = [
> ```

I would add a namespace.

---

*[django_pain/views.py, line 14 at r1](https://reviewable.io/reviews/stinovlas/django-pain/9#-LCiDLDoBhxTgfUrrbcV:-LCiDLDoBhxTgfUrrbcW:bz03bt8) ([raw file](https://github.com/stinovlas/django-pain/blob/43f892155a9361f95837b2ff35492f061010896a/django_pain/views.py#L14)):*
> ```Python
>     def get_context_data(self, **kwargs):
>         """Get context data."""
>         context = kwargs
> ```

It's better to call the parent.

---

*[django_pain/templates/django_pain/payments_list.html, line 4 at r1](https://reviewable.io/reviews/stinovlas/django-pain/9#-LCiDW6u9dEapClcJJuQ:-LCiDW6u9dEapClcJJuR:by6lgig) ([raw file](https://github.com/stinovlas/django-pain/blob/43f892155a9361f95837b2ff35492f061010896a/django_pain/templates/django_pain/payments_list.html#L4)):*
> ```HTML
> 
> {% for payment in payments %}
>     <b>{% trans "Payment" %} {{ payment.identifier }} ({{ payment.state }})</b>
> ```

How do you expect this template to be integrated into a website?

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/9)*

**Comment by stinovlas** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[django_pain/urls.py, line 6 at r1](https://reviewable.io/reviews/stinovlas/django-pain/9#-LCiDH0iCpmYqmrPiAQ-:-LDC-FNHE1Avo1nkOefH:b-e5ix8) ([raw file](https://github.com/stinovlas/django-pain/blob/43f892155a9361f95837b2ff35492f061010896a/django_pain/urls.py#L6)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

I would add a namespace.
</blockquote></details>

Agreed, I added namespace `pain`.  However, the user will probably add their own namespace anyway, when including `django_pain` urls.

---

*[django_pain/views.py, line 14 at r1](https://reviewable.io/reviews/stinovlas/django-pain/9#-LCiDLDoBhxTgfUrrbcV:-LDC-XAn3H_2-JiUKMs7:b-975hyi) ([raw file](https://github.com/stinovlas/django-pain/blob/43f892155a9361f95837b2ff35492f061010896a/django_pain/views.py#L14)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

It's better to call the parent.
</blockquote></details>

You're right. In this particular case it does noting interesting, but it might do in a future, if class ancestors are changed. Updated.

---

*[django_pain/templates/django_pain/payments_list.html, line 4 at r1](https://reviewable.io/reviews/stinovlas/django-pain/9#-LCiDW6u9dEapClcJJuQ:-LDC-vge0DzwgqedlEYp:bykeimf) ([raw file](https://github.com/stinovlas/django-pain/blob/43f892155a9361f95837b2ff35492f061010896a/django_pain/templates/django_pain/payments_list.html#L4)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

How do you expect this template to be integrated into a website?
</blockquote></details>

I added `block` tags and (very simple) `base.html` template. I expect that website will override the base template. This template can be also overriden. It's just the first simple template without pagination or anything sophisticated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/9)*

**Comment by ziima** [comment]
Reviewed 1 of 4 files at r1, 5 of 8 files at r2.
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[django_pain/urls.py, line 6 at r1](https://reviewable.io/reviews/stinovlas/django-pain/9#-LCiDH0iCpmYqmrPiAQ-:-LDGxlvK2sdgZ3cptcUu:bm2ij3h) ([raw file](https://github.com/stinovlas/django-pain/blob/43f892155a9361f95837b2ff35492f061010896a/django_pain/urls.py#L6)):*
<details><summary><i>Previously, stinovlas (Jan Musílek) wrote…</i></summary><blockquote>

Agreed, I added namespace `pain`.  However, the user will probably add their own namespace anyway, when including `django_pain` urls.
</blockquote></details>

That's not the same type of namespace :)

---

*[django_pain/views.py, line 14 at r1](https://reviewable.io/reviews/stinovlas/django-pain/9#-LCiDLDoBhxTgfUrrbcV:-LDGxwbK6ZdbXG9qavO6:b-up9o59) ([raw file](https://github.com/stinovlas/django-pain/blob/43f892155a9361f95837b2ff35492f061010896a/django_pain/views.py#L14)):*
<details><summary><i>Previously, stinovlas (Jan Musílek) wrote…</i></summary><blockquote>

You're right. In this particular case it does noting interesting, but it might do in a future, if class ancestors are changed. Updated.
</blockquote></details>

The `TemplateView` adds the view instance into the context, that might be helpful.

---

*[django_pain/views.py, line 15 at r2](https://reviewable.io/reviews/stinovlas/django-pain/9#-LDGzKxf1jjFFqw7c2H5:-LDGzKxf1jjFFqw7c2H6:b-xwvede) ([raw file](https://github.com/stinovlas/django-pain/blob/61b2620f84ad06321757dec99e4fca5f45160596/django_pain/views.py#L15)):*
> ```Python
>         """Get context data."""
>         context = super().get_context_data(**kwargs)
>         context['payments'] = BankPayment.objects.all()
> ```

`ListView` is designed for displaying a list of objects.

---

*[django_pain/templates/django_pain/base.html, line 5 at r2](https://reviewable.io/reviews/stinovlas/django-pain/9#-LDGyghv4BzOqJiHdSzv:-LDGyghv4BzOqJiHdSzw:b-hibrgw) ([raw file](https://github.com/stinovlas/django-pain/blob/61b2620f84ad06321757dec99e4fca5f45160596/django_pain/templates/django_pain/base.html#L5)):*
> ```HTML
>     <head>
>         <meta charset="utf-8">
>         <title>{% block title %}django_pain{% endblock %}</title>
> ```

"Django Pain" would be better title.

---

*[django_pain/tests/utils.py, line 11 at r2](https://reviewable.io/reviews/stinovlas/django-pain/9#-LDGz6qj-EbUCX_19XEe:-LDGz6qj-EbUCX_19XEf:bwysw6v) ([raw file](https://github.com/stinovlas/django-pain/blob/61b2620f84ad06321757dec99e4fca5f45160596/django_pain/tests/utils.py#L11)):*
> ```Python
> 
> def get_payment(**kwargs: Any) -> BankPayment:
>     """Create payment object."""
> ```

Maybe `make_payment`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/9)*

**Comment by ziima** [comment]
Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[django_pain/urls.py, line 6 at r1](https://reviewable.io/reviews/stinovlas/django-pain/9#-LCiDH0iCpmYqmrPiAQ-:-LDGzjTj1urOT2xE-nnG:b-8eogq1) ([raw file](https://github.com/stinovlas/django-pain/blob/43f892155a9361f95837b2ff35492f061010896a/django_pain/urls.py#L6)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

That's not the same type of namespace :)
</blockquote></details>

:ok: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/9)*

**Comment by ziima** [comment]
Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[django_pain/urls.py, line 6 at r1](https://reviewable.io/reviews/stinovlas/django-pain/9#-LCiDH0iCpmYqmrPiAQ-:-LDGzsBO-eHqyPOl1Hv4:b32w0x) ([raw file](https://github.com/stinovlas/django-pain/blob/43f892155a9361f95837b2ff35492f061010896a/django_pain/urls.py#L6)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

:ok: 
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/9)*

**Comment by stinovlas** [comment]
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[django_pain/tests/utils.py, line 11 at r2](https://reviewable.io/reviews/stinovlas/django-pain/9#-LDGz6qj-EbUCX_19XEe:-LDH0AxR-9y4GlXb0_9G:b5lxc1b) ([raw file](https://github.com/stinovlas/django-pain/blob/61b2620f84ad06321757dec99e4fca5f45160596/django_pain/tests/utils.py#L11)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

Maybe `make_payment`?
</blockquote></details>

Make does not sound right. Maybe `create_payment` or `new_payment`? However `get_payment` seems fine to me.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/9)*

**Comment by ziima** [comment]
*[django_pain/tests/utils.py, line 11 at r2](https://reviewable.io/reviews/stinovlas/django-pain/9#-LDGz6qj-EbUCX_19XEe:-LDH2C928_OtrruijIBN:b-gg99lp) ([raw file](https://github.com/stinovlas/django-pain/blob/61b2620f84ad06321757dec99e4fca5f45160596/django_pain/tests/utils.py#L11)):*
<details><summary><i>Previously, stinovlas (Jan Musílek) wrote…</i></summary><blockquote>

Make does not sound right. Maybe `create_payment` or `new_payment`? However `get_payment` seems fine to me.
</blockquote></details>

`create_payment` strongly resembles `BankPayment.objects.create(...)`, `get_payment` similarly `objects.get(...)`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/9)*

**Comment by stinovlas** [comment]
*[django_pain/tests/utils.py, line 11 at r2](https://reviewable.io/reviews/stinovlas/django-pain/9#-LDGz6qj-EbUCX_19XEe:-LDLDXruAm8CN2KVgfkM:bp842x9) ([raw file](https://github.com/stinovlas/django-pain/blob/61b2620f84ad06321757dec99e4fca5f45160596/django_pain/tests/utils.py#L11)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

`create_payment` strongly resembles `BankPayment.objects.create(...)`, `get_payment` similarly `objects.get(...)`.
</blockquote></details>

OK, but `make_payment` has its own meaning, which is different than "create new payment object". `get_payment` returns object instance, same as `objects.get(...)` so the resemblance actually makes sense.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/9)*

**Comment by ziima** [comment]
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[django_pain/tests/utils.py, line 11 at r2](https://reviewable.io/reviews/stinovlas/django-pain/9#-LDGz6qj-EbUCX_19XEe:-LDLF9i-8bpTDjntgZYA:b98ua5m) ([raw file](https://github.com/stinovlas/django-pain/blob/61b2620f84ad06321757dec99e4fca5f45160596/django_pain/tests/utils.py#L11)):*
<details><summary><i>Previously, stinovlas (Jan Musílek) wrote…</i></summary><blockquote>

OK, but `make_payment` has its own meaning, which is different than "create new payment object". `get_payment` returns object instance, same as `objects.get(...)` so the resemblance actually makes sense.
</blockquote></details>

Right, "make payment" didn't cross my mind. OK then.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/9)*

**Comment by stinovlas** [comment]
Review status: 5 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[django_pain/views.py, line 15 at r2](https://reviewable.io/reviews/stinovlas/django-pain/9#-LDGzKxf1jjFFqw7c2H5:-LDLUbalDL8rrMK3QiAN:b-onykyu) ([raw file](https://github.com/stinovlas/django-pain/blob/61b2620f84ad06321757dec99e4fca5f45160596/django_pain/views.py#L15)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

`ListView` is designed for displaying a list of objects.
</blockquote></details>

Yeah, I was reluctant to use it, but since `BankPayment` is a Model, it actually could save some typing. Corrected.

---

*[django_pain/templates/django_pain/base.html, line 5 at r2](https://reviewable.io/reviews/stinovlas/django-pain/9#-LDGyghv4BzOqJiHdSzv:-LDLUmF1EASCWuqwqg3K:bt2vr1b) ([raw file](https://github.com/stinovlas/django-pain/blob/61b2620f84ad06321757dec99e4fca5f45160596/django_pain/templates/django_pain/base.html#L5)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

"Django Pain" would be better title.
</blockquote></details>

Fixed.

---

*[django_pain/tests/utils.py, line 11 at r2](https://reviewable.io/reviews/stinovlas/django-pain/9#-LDGz6qj-EbUCX_19XEe:-LDLUvEG43FZ6dbDVD-I:b-ratfla) ([raw file](https://github.com/stinovlas/django-pain/blob/61b2620f84ad06321757dec99e4fca5f45160596/django_pain/tests/utils.py#L11)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

Right, "make payment" didn't cross my mind. OK then.
</blockquote></details>

OK, lets leave it at `get_payment`. You may close the discussion.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/9)*

**Comment by ziima** [comment]
:lgtm:

---

Reviewed 2 of 8 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/9#-:-LDMAZnN0xWy5BgiWfB6:bnfp4nl)*

**Pull request merged**
