### PR TITLE
Bulk payments processing

### LINKED ISSUE #19: Change process_payments to allow bulk processing
Processing payments now takes one payment at a time and feeds it to the processor. However, in some cases (such as communication through REST API) sending payments in bulk is much more efficient. We should extend the interface to allow bulk processing.

### Proposed implementation
* Add new method `process_payments(self, payments: Iterable[BankPayment]) -> Iterable[bool]` to `processors.common.AbstractPaymentProcessor`.
* Drop old method `process_payment(self, payment: BankPayment) -> bool` from `processors.common.AbstractPaymentProcessor`.
* Update `management.commands.process_payments`appropriately.

This change breaks backwards compatibility and minor version should be bumped up.

### PR DESCRIPTION
**Pull request by stinovlas**
Closes #19.

---
This change is [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/20)

### CODE REVIEW

**Comment by ziima** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @stinovlas and @ziima)

---

*[django_pain/management/commands/process_payments.py, line 37 at r1](https://reviewable.io/reviews/stinovlas/django-pain/20#-LFWrda46fIXcQCYGVMk:-LFWrda46fIXcQCYGVMl:bdnilz) ([raw file](https://github.com/stinovlas/django-pain/blob/e60729a9b23b42a5e0b14e1322f4a78957909a10/django_pain/management/commands/process_payments.py#L37)):*
> ```Python
>         for processor in processors:
>             if not payments:
>                 break
> ```

This condition can be much higher.

---

*[django_pain/management/commands/process_payments.py, line 39 at r1](https://reviewable.io/reviews/stinovlas/django-pain/20#-LFWsIhl9OwJ8CToLv4Z:-LFWsIhl9OwJ8CToLv4_:bsee6c8) ([raw file](https://github.com/stinovlas/django-pain/blob/e60729a9b23b42a5e0b14e1322f4a78957909a10/django_pain/management/commands/process_payments.py#L39)):*
> ```Python
>                 break
> 
>             results = processor.process_payments([deepcopy(payment) for payment in payments])
> ```

This could be a lot of payments, which is not very memory efficient. Do we care?

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/20)*

**Comment by stinovlas** [comment]
Review status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ziima)

---

*[django_pain/management/commands/process_payments.py, line 37 at r1](https://reviewable.io/reviews/stinovlas/django-pain/20#-LFWrda46fIXcQCYGVMk:-LFWzDur0PUHvpHF0tpC:b-mush5j) ([raw file](https://github.com/stinovlas/django-pain/blob/e60729a9b23b42a5e0b14e1322f4a78957909a10/django_pain/management/commands/process_payments.py#L37)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

This condition can be much higher.
</blockquote></details>

There can be another condition higher, but then I still have to keep it here. I'm changing the content of payments variable and I don't want to call `process_payments` on empty list.

---

*[django_pain/management/commands/process_payments.py, line 39 at r1](https://reviewable.io/reviews/stinovlas/django-pain/20#-LFWsIhl9OwJ8CToLv4Z:-LFWy9aV6VsAPBzOJmTB:b-4a3jf5) ([raw file](https://github.com/stinovlas/django-pain/blob/e60729a9b23b42a5e0b14e1322f4a78957909a10/django_pain/management/commands/process_payments.py#L39)):*
<details><summary><i>Previously, ziima (Vlastimil Zíma) wrote…</i></summary><blockquote>

This could be a lot of payments, which is not very memory efficient. Do we care?
</blockquote></details>

Well, I could simply replace this with a generator:
```python
results = processor.process_payments(deepcopy(payment) for payment in payments)
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/20)*

**Comment by stinovlas** [comment]
Review status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ziima)

---

*[django_pain/management/commands/process_payments.py, line 37 at r1](https://reviewable.io/reviews/stinovlas/django-pain/20#-LFWrda46fIXcQCYGVMk:-LFXClnWA5Zz7Sk0TjQJ:bc31dpc) ([raw file](https://github.com/stinovlas/django-pain/blob/e60729a9b23b42a5e0b14e1322f4a78957909a10/django_pain/management/commands/process_payments.py#L37)):*
<details><summary><i>Previously, stinovlas (Jan Musílek) wrote…</i></summary><blockquote>

There can be another condition higher, but then I still have to keep it here. I'm changing the content of payments variable and I don't want to call `process_payments` on empty list.
</blockquote></details>

I'd prefer to leave it where it is.

---

*[django_pain/management/commands/process_payments.py, line 39 at r1](https://reviewable.io/reviews/stinovlas/django-pain/20#-LFWsIhl9OwJ8CToLv4Z:-LFXBRk-2FrUCCPGYsRm:bar2phu) ([raw file](https://github.com/stinovlas/django-pain/blob/e60729a9b23b42a5e0b14e1322f4a78957909a10/django_pain/management/commands/process_payments.py#L39)):*
<details><summary><i>Previously, stinovlas (Jan Musílek) wrote…</i></summary><blockquote>

Well, I could simply replace this with a generator:
```python
results = processor.process_payments(deepcopy(payment) for payment in payments)
```
</blockquote></details>

I changed list to generator. I had to use `# pragma: no cover`, because of how coverage analysis of zipped generators. See https://stackoverflow.com/questions/35317757/python-unittest-branch-coverage-seems-to-miss-executed-generator-in-zip

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/20)*

**Comment by ziima** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/20#-:-LFXQfiy-H2ZkcuY75JS:bnfp4nl)*

**Review by ziima — APPROVED** [review]

**Pull request merged**
