### PR TITLE
Add uuid field to BankPayment

### LINKED ISSUE #15: Generate UUID for payments
Add field `uuid` of type [`UUIDField`](https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.UUIDField) to `BankPayment` model in order to generate nice unique identifier for each payment. Values will be generated by `uuid.uuid4()` function.

This identifier will be used by payment processors in communication with various systems to prevent data mismatch in case of broken connection or other unexpected events.

### PR DESCRIPTION
**Pull request by stinovlas**
Closes #15.

Migration in this commit may cause trouble, because it generates the same values for unique fields. Normally, it would require three different migrations to overcome this problem (one creating non-unique null field, second one generating unique values and the third one altering field to not-null unique). However, django-pain is still in pre-alpha state and violent changes must be expected.

---
This change is [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/16)

### CODE REVIEW

**Comment by tpazderka** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @stinovlas)

---

*[django_pain/migrations/0006_bankpayment_uuid.py, line 7 at r2](https://reviewable.io/reviews/stinovlas/django-pain/16#-LEntBbF-lPCWc-WOylr:-LEntBbG8z25oYr_QkeE:b-nnsvw9) ([raw file](https://github.com/stinovlas/django-pain/blob/b3c5dc649ae763c493dba554c32c44b6976900a7/django_pain/migrations/0006_bankpayment_uuid.py#L7)):*
> ```Python
> 
> 
> class Migration(migrations.Migration):
> ```

I think that the migration script should be included. As long as there are two entries in the DB, this migration cannot be applied automatically and quite a lot of manual work is needed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/16)*

**Comment by stinovlas** [comment]
Review status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @tpazderka)

---

*[django_pain/migrations/0006_bankpayment_uuid.py, line 7 at r2](https://reviewable.io/reviews/stinovlas/django-pain/16#-LEntBbF-lPCWc-WOylr:-LEnx0PgAhgbNvONW6Y-:b-896fix) ([raw file](https://github.com/stinovlas/django-pain/blob/b3c5dc649ae763c493dba554c32c44b6976900a7/django_pain/migrations/0006_bankpayment_uuid.py#L7)):*
<details><summary><i>Previously, tpazderka wrote…</i></summary><blockquote>

I think that the migration script should be included. As long as there are two entries in the DB, this migration cannot be applied automatically and quite a lot of manual work is needed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/16)*

**Comment by tpazderka** [comment]
Reviewed 3 of 3 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/16)*

**Comment by tpazderka** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/stinovlas/django-pain/16#-:-LEnyC006kzuPc7UMNLB:bnfp4nl)*

**Review by tpazderka — APPROVED** [review]

**Pull request merged**
